---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "vcf2genome"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::vcf2genome=0.91"
